/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RegistroUsuarios;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

public class AppTest 
{
    RegistroUsuarios ru;

    @Before public void setUp()
    {
        ru = new RegistroUsuarios();
    }

    @Test public void testUsuario() 
    {
        assertTrue(ru.usuarios("Rodrigo") == true);
    }

    @Test public void testRegistro() 
    {
        assertNotNull(ru.registrar("Nicolas", 31, "Col. del Bosque", "Lenguaje de programacion Java"));
    }

    @Test public void testDepositoTiempo() 
    {
        assertNotNull(ru.registrarTiempo(123, "Grecia"));
    }

}
