/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RegistroUsuarios;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest 
{
    RegistroUsuarios ru;

    @Test public void testAppHasAGreeting() 
    {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testRegistro() 
    {
        ru = new RegistroUsuarios();

        assertTrue(ru.usuarios("Rodrigo") == true);
    }

}
